version: '3.8'

services:
  app:
    build: .
    image: lyxatang/energy-simulator:latest
    container_name: energy-sim
    ports:
      - "6080:6080"  # noVNC browser port
      - "5900:5900"  # VNC port
    volumes:
      - .:/app
    environment:
      - DISPLAY=:99
      # - SDL_VIDEODRIVER=dummy # this makes it headless mode if not commented
      - SDL_AUDIODRIVER=dummy
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true